import type { Metadata } from "next";
import { Inter, Source_Code_Pro } from "next/font/google";
import { RootProvider } from "./rootProvider";
import Script from 'next/script';
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_PROJECT_NAME,
  description: "Generated by `create-onchain`, a Next.js template for OnchainKit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${sourceCodePro.variable}`}>
        <Script
          id="base-app-id"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              const meta = document.createElement('meta');
              meta.name = 'base:app_id';
              meta.content = '696d16d7c0ab25addaaaf46a';
              document.head.appendChild(meta);
            `
          }}
        />
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}